const ROULETTE_EZUGI_LIST = [{
        description: 'Skyline Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '221008',
        redisKey: 'ezugi-221008',
        path: 'ezugi-skyline-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Italian Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '1000',
        redisKey: 'ezugi-1000',
        path: 'ezugi-italian-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Auto Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '5001',
        redisKey: 'ezugi-5001',
        path: 'ezugi-auto-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Speed Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '221000',
        redisKey: 'ezugi-221000',
        path: 'ezugi-speed-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Speed Auto Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '221002',
        redisKey: 'ezugi-221002',
        path: 'ezugi-speed-auto-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Diamond Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '221003',
        redisKey: 'ezugi-221003',
        path: 'ezugi-diamond-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Prestige Auto Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '221004',
        redisKey: 'ezugi-221004',
        path: 'ezugi-prestige-auto-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Namaste Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '221005',
        redisKey: 'ezugi-221005',
        path: 'ezugi-namaste-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Roleta da Sorte',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '241000',
        redisKey: 'ezugi-241000',
        path: 'ezugi-roleta-da-sorte',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Casino Marina Roulette 1',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '321000',
        redisKey: 'ezugi-321000',
        path: 'ezugi-casino-marina-roulette-1',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Casino Marina Roulette 2',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '321001',
        redisKey: 'ezugi-321001',
        path: 'ezugi-casino-marina-roulette-2',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Spanish Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '411000',
        redisKey: 'ezugi-411000',
        path: 'ezugi-spanish-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Ruleta del Sol',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '431000',
        redisKey: 'ezugi-431000',
        path: 'ezugi-ruleta-del-sol',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'EZ Dealer Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '481000',
        redisKey: 'ezugi-481000',
        path: 'ezugi-ez-dealer-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'EZ Dealer Roulette Thai',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '481001',
        redisKey: 'ezugi-481001',
        path: 'ezugi-ez-dealer-roulette-thai',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'EZ Dealer Roulette Japanese',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '481002',
        redisKey: 'ezugi-481002',
        path: 'ezugi-ez-dealer-roulette-japanese',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'EZ Dealer Roulette Mandarin',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '481003',
        redisKey: 'ezugi-481003',
        path: 'ezugi-ez-dealer-roulette-mandarin',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'EZ Dealer Roulette Brazil',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '481004',
        redisKey: 'ezugi-481004',
        path: 'ezugi-ez-dealer-roulette-brazil',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Turkish Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '501000',
        redisKey: 'ezugi-501000',
        path: 'ezugi-turkish-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Ultimate Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '541000',
        redisKey: 'ezugi-541000',
        path: 'ezugi-ultimate-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Russian Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '601000',
        redisKey: 'ezugi-601000',
        path: 'ezugi-russian-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Portomaso Roulette 2',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '611000',
        redisKey: 'ezugi-611000',
        path: 'ezugi-portomaso-roulette-2',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Oracle Real Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '611001',
        redisKey: 'ezugi-611001',
        path: 'ezugi-oracle-real-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'Oracle 360 Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '611003',
        redisKey: 'ezugi-611003',
        path: 'ezugi-oracle-360-roulette',
        use: true,
        from: 'ezugi',
    },
    {
        description: 'VIP Roulette',
        providerAlias: 'ezugi',
        providerId: 'ezugi',
        refGameId: '611007',
        redisKey: 'ezugi-611007',
        path: 'ezugi-vip-roulette',
        use: true,
        from: 'ezugi',
    },
];
const ROULETTE_EZUGI_LIST_ACTIVE_KEYS = ROULETTE_EZUGI_LIST.map((g) => g.redisKey);
export {
    ROULETTE_EZUGI_LIST,
    ROULETTE_EZUGI_LIST_ACTIVE_KEYS,
};
//# sourceMappingURL=list.ezugi.js.map